# Generated by Django 4.2 on 2023-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_movie', models.CharField(max_length=255)),
                ('seat_id', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
