# Generated by Django 4.2 on 2023-04-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 13, 11, 9, 990512)),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
