# Generated by Django 4.2 on 2023-04-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0004_alter_seat_show_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='title_movie',
        ),
        migrations.AlterField(
            model_name='seat',
            name='show_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_service.showtime'),
        ),
    ]
