# Generated by Django 4.2 on 2023-04-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0005_showtime_remove_seat_title_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
    ]
