# Generated by Django 4.2 on 2023-04-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0006_showtime_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='show_time',
            new_name='showtime_id',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='start_time',
            new_name='showtime',
        ),
    ]
